# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('naturalUser', '__first__'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='naturalUser.NaturalUser'),
            preserve_default=False,
        ),
    ]
