# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ong', '0001_initial'),
        ('animals', '0002_adopt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='animal',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='animals.Animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='ong',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ong.ONG'),
            preserve_default=False,
        ),
    ]
