# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 03:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('name', models.TextField(max_length=200, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('directions', models.TextField(max_length=200, null=True)),
                ('avatar', models.ImageField(upload_to='ong/avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='ONGUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ong.ONG')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
