# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
    ]
