# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='case',
            field=models.SmallIntegerField(choices=[(1, 'Abandono en la calle'), (2, 'Exposición a temperaturas extremas'), (3, 'Falta de agua'), (4, 'Falta de comida'), (5, 'Violencia'), (6, 'Venta ambulante')], default=1),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='color',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='directions',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Macho'), (2, 'Hembra'), (3, 'Desconocido')], default=3),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=django.utils.timezone.now, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=django.utils.timezone.now, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Reportada'), (2, 'Consolidada'), (3, 'Verificada'), (4, 'Cerrada'), (5, 'Desechada')], default=1),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='wounded',
            field=models.SmallIntegerField(choices=[(1, 'Sí'), (2, 'No'), (3, 'Desconocido')], default=3),
        ),
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='complaints/'),
        ),
    ]
